<?php
$this->_setLayout('layout/base', 'content');

$this->_layout->title = 'test > 登陆';

$this->_layout->css_files[] = 'http://localhost/wordpress/wp-admin/css/wp-admin.css?ver=3.4.2';
$this->_layout->css_files[] = 'http://localhost/wordpress/wp-admin/css/colors-fresh.css?ver=3.4.2';

$this->_layout->head_txt .= "<meta name='robots' content='noindex,nofollow' />";
?>
	<div id="login">
		<h1><a href="http://cn.wordpress.org/" title="基于 WordPress">test</a></h1>
	<p class="message">	您已登出。<br />
</p>

<form name="loginform" id="loginform" action="http://localhost/wordpress/wp-login.php" method="post">
	<p>
		<label for="user_login">用户名<br />
		<input type="text" name="log" id="user_login" class="input" value="" size="20" tabindex="10" /></label>
	</p>
	<p>
		<label for="user_pass">密码<br />
		<input type="password" name="pwd" id="user_pass" class="input" value="" size="20" tabindex="20" /></label>
	</p>
	<p class="forgetmenot"><label for="rememberme"><input name="rememberme" type="checkbox" id="rememberme" value="forever" tabindex="90" /> 记住我的登录信息</label></p>
	<p class="submit">
		<input type="submit" name="wp-submit" id="wp-submit" class="button-primary" value="登录" tabindex="100" />
		<input type="hidden" name="redirect_to" value="http://localhost/wordpress/wp-admin/" />
		<input type="hidden" name="testcookie" value="1" />
	</p>
</form>

<p id="nav">
<a href="http://localhost/wordpress/wp-login.php?action=lostpassword" title="找回密码">忘记密码？</a>
</p>

<script type="text/javascript">
function wp_attempt_focus(){
setTimeout( function(){ try{
d = document.getElementById('user_login');
d.focus();
d.select();
} catch(e){}
}, 200);
}

if(typeof wpOnload=='function')wpOnload();
</script>

	<p id="backtoblog"><a href="http://localhost/wordpress/" title="不知道自己在哪？">&larr; 回到 test</a></p>
	
	</div>

	
		<div class="clear"></div>
