<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="zh-CN">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title><?=htmlspecialchars($title)?></title>
<?
//这里是头部css
if (isset($css_files)) {
	foreach ($css_files as $src) {
		echo "<link rel='stylesheet' href='{$src}' type='text/css' />\n";
	}
}

if (isset($head_txt)) {
	echo $head_txt;
}

?>
</head>
<body>
	<?=$content?>

<?//尾部js
if (isset($js_files)) {
	foreach ($js_files as $src) {
		echo "<script src='{$src}'></script>\n";
	}
}
if (isset($footer_txt)) {
	echo $footer_txt;
}
?>

</body>
</html>
