<?php
$this->_setLayout('layout/base', 'content');

$this->_layout->title = '编辑新闻';


widget\user::top();
?>


<div>
<?if($msg):?>
<h2><?=$msg?></h2>
<?endif?>

<form action="<?=$posturl?>" method="post">
<input type="hidden" name="token" value="<?=$token?>" />
<input type="hidden" name="id" value="<?=$id?>" />
标题: <input type='text' name='title' value="<?=$title?>" /> <br />
内容: <textarea name='content'><?=htmlspecialchars($content)?></textarea>
<button type="sumbit">提交</button>
</form>
</div>
